from tkinter import *

root = Tk()

root.title("Irregular Verb Transformer")
root.geometry('500x600')
# Setea el background
bg = PhotoImage(file = "./background.png")
lblBg = Label(root, image = bg)
lblBg.place(x = -40, y = -4)

verbs = [
    ["arise", "arisen", "surgir / elevarse"],
    ["awake", "awoken", "despertar(se)"],
    ["be", "been", "ser / estar"],
    ["bear", "borne", "soportar / llevar"],
    ["beat", "beaten", "golpear / vencer"],
    ["become", "become", "llegar a ser / convertirse"],
    ["begin", "begun", "empezar"],
    ["bend", "bent", "doblar / inclinarse"],
    ["bet", "bet", "apostar"],
    ["bid", "bid", "ofertar / pujar"],
    ["bind", "bound", "atar / encuadernar"],
    ["bite", "bitten", "morder"],
    ["bleed", "bled", "sangrar"],
    ["blow", "blown", "soplar"],
    ["break", "broken", "romper"],
    ["breed", "bred", "criar / reproducirse"],
    ["bring", "brought", "traer"],
    ["broadcast", "broadcast", "transmitir"],
    ["build", "built", "construir"],
    ["burn", "burnt/burned", "quemar"],
    ["burst", "burst", "estallar / reventar"],
    ["buy", "bought", "comprar"],
    ["cast", "cast", "lanzar / repartir (roles)"],
    ["catch", "caught", "atrapar"],
    ["choose", "chosen", "elegir"],
    ["cling", "clung", "agarrarse / adherirse"],
    ["come", "come", "venir"],
    ["cost", "cost", "costar"],
    ["creep", "crept", "arrastrarse"],
    ["cut", "cut", "cortar"],
    ["deal", "dealt", "tratar / repartir (cartas)"],
    ["dig", "dug", "cavar"],
    ["dive", "dived", "bucear / sumergirse"],
    ["do", "done", "hacer"],
    ["draw", "drawn", "dibujar"],
    ["dream", "dreamt/dreamed", "soñar"],
    ["drink", "drunk", "beber"],
    ["drive", "driven", "conducir / manejar"],
    ["eat", "eaten", "comer"],
    ["fall", "fallen", "caer"],
    ["feed", "fed", "alimentar"],
    ["feel", "felt", "sentir"],
    ["fight", "fought", "pelear"],
    ["find", "found", "encontrar"],
    ["flee", "fled", "huir"],
    ["fling", "flung", "lanzar / arrojar"],
    ["fly", "flown", "volar"],
    ["forbid", "forbidden", "prohibir"],
    ["forget", "forgotten", "olvidar"],
    ["forgive", "forgiven", "perdonar"],
    ["freeze", "frozen", "congelar"],
    ["get", "got", "obtener / llegar a ser"],
    ["give", "given", "dar"],
    ["go", "gone", "ir"],
    ["grind", "ground", "moler"],
    ["grow", "grown", "crecer / cultivar"],
    ["hang", "hung", "colgar"],
    ["have", "had", "tener / haber"],
    ["hear", "heard", "oír"],
    ["hide", "hidden", "esconder"],
    ["hit", "hit", "golpear / pegar"],
    ["hold", "held", "sostener / agarrar"],
    ["hurt", "hurt", "doler / lastimar"],
    ["keep", "kept", "guardar / mantener"],
    ["kneel", "knelt", "arrodillarse"],
    ["knit", "knit", "tejer"],
    ["know", "known", "saber / conocer"],
    ["lay", "laid", "poner / colocar"],
    ["lead", "led", "liderar / guiar"],
    ["lean", "leant/leaned", "inclinarse / apoyarse"],
    ["leap", "leapt/leaped", "saltar / brincar"],
    ["learn", "learnt/learned", "aprender"],
    ["leave", "left", "dejar / irse"],
    ["lend", "lent", "prestar"],
    ["let", "let", "permitir / dejar"],
    ["lie", "lain", "estar acostado / yacer"],
    ["light", "lit", "encender / iluminar"],
    ["lose", "lost", "perder"],
    ["make", "made", "hacer / fabricar"],
    ["mean", "meant", "significar"],
    ["meet", "met", "encontrar / conocer a alguien"],
    ["mow", "mown", "cortar césped / segar"],
    ["pay", "paid", "pagar"],
    ["prove", "proven", "probar / demostrar"],
    ["put", "put", "poner / colocar"],
    ["quit", "quit", "renunciar / dejar"],
    ["read", "read", "leer"],
    ["ride", "ridden", "montar / andar en"],
    ["ring", "rung", "llamar por teléfono / sonar"],
    ["rise", "risen", "elevarse / levantarse"],
    ["run", "run", "correr"],
    ["saw", "sawn", "serrar"],
    ["say", "said", "decir"],
    ["see", "seen", "ver"],
    ["seek", "sought", "buscar"],
    ["sell", "sold", "vender"],
    ["send", "sent", "enviar"],
    ["set", "set", "colocar / establecer"],
    ["sew", "sewn", "coser"],
    ["shake", "shaken", "sacudir / agitar"],
    ["shed", "shed", "derramar / desprenderse"],
    ["shine", "shone", "brillar / relucir"],
    ["shoot", "shot", "disparar"],
    ["show", "shown", "mostrar"],
    ["shrink", "shrunk", "encogerse / reducirse"],
    ["shut", "shut", "cerrar"],
    ["sing", "sung", "cantar"],
    ["sink", "sunk", "hundirse"],
    ["sit", "sat", "sentarse"],
    ["sleep", "slept", "dormir"],
    ["slide", "slid", "deslizarse"],
    ["sling", "slung", "lanzar / tirar con honda"],
    ["smell", "smelt/smelled", "oler"],
    ["sow", "sown", "sembrar"],
    ["speak", "spoken", "hablar"],
    ["speed", "sped", "acelerar / ir rápido"],
    ["spell", "spelt/spelled", "deletrear"],
    ["spend", "spent", "gastar / pasar tiempo"],
    ["spill", "spilt/spilled", "derramar"],
    ["spin", "spun", "girar / hilar"],
    ["spit", "spat", "escupir"],
    ["split", "split", "dividir / partir"],
    ["spoil", "spoilt/spoiled", "estropear / malcriar"],
    ["spread", "spread", "extender / propagar"],
    ["spring", "sprung", "saltar / brotar"],
    ["stand", "stood", "estar de pie / soportar"],
    ["steal", "stolen", "robar"],
    ["stick", "stuck", "pegar / atascarse"],
    ["sting", "stung", "picar (insecto)"],
    ["stink", "stunk", "apestar"],
    ["strike", "struck", "golpear / huelga"],
    ["string", "strung", "ensartar / encordar"],
    ["strive", "striven", "esforzarse"],
    ["swear", "sworn", "jurar / maldecir"],
    ["sweep", "swept", "barrer"],
    ["swell", "swollen", "hincharse"],
    ["swim", "swum", "nadar"],
    ["swing", "swung", "columpiar / balancear"],
    ["take", "taken", "tomar / llevar"],
    ["teach", "taught", "enseñar"],
    ["tear", "torn", "rasgar / romper"],
    ["tell", "told", "decir / contar"],
    ["think", "thought", "pensar"],
    ["throw", "thrown", "lanzar / tirar"],
    ["thrust", "thrust", "empujar / introducir"],
    ["tread", "trodden", "pisar / caminar sobre"],
    ["understand", "understood", "entender"],
    ["undertake", "undertaken", "emprender"],
    ["upset", "upset", "molestar / trastornar"],
    ["wake", "woken", "despertar"],
    ["wear", "worn", "usar (ropa) / llevar puesto"],
    ["weave", "woven", "tejer"],
    ["weep", "wept", "llorar"],
    ["wet", "wet", "mojar / humedecer"],
    ["win", "won", "ganar"],
    ["wind", "wound", "enrollar / dar cuerda"],
    ["wring", "wrung", "retorcer / escurrir"],
    ["write", "written", "escribir"]
]

root.mainloop()